import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { detectPastedFormat, parsePastedDependencies } from "../src/pastedDepsParser.js";

// ── fixture-like content blobs ──────────────────────────────────────────────────

const PACKAGE_LOCK_V2 = `{
  "name": "myapp",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "myapp",
      "version": "1.0.0",
      "dependencies": { "lodash": "^4.17.21" }
    },
    "node_modules/lodash": {
      "version": "4.17.21",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
    }
  }
}`;

const PACKAGE_LOCK_V1 = `{
  "name": "myapp",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "lodash": {
      "version": "4.17.21",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
    }
  }
}`;

const BUN_LOCK = `{
  "lockfileVersion": 1,
  "workspaces": {
    "": {
      "name": "my-app",
      "dependencies": { "lodash": "^4.17.21" }
    }
  },
  "packages": {
    "lodash@4.17.21": ["lodash@4.17.21", "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz#679591c", {}, "sha512-v2kDEe57lecTulD"]
  }
}`;

const PACKAGE_JSON = `{
  "name": "myapp",
  "version": "1.0.0",
  "dependencies": {
    "lodash": "^4.17.21",
    "vite": "^5.0.0"
  },
  "devDependencies": {
    "eslint": "^8.0.0"
  }
}`;

const PNPM_LOCK = `lockfileVersion: 5.4

dependencies:
  lodash: 4.17.21

packages:

  /lodash/4.17.21:
    resolution: {integrity: sha512-v2kDEe57lecTulD}
    dev: false
`;

const YARN_CLASSIC_LOCK = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c"
  integrity sha512-v2kDEe57lecTulD
`;

const YARN_BERRY_LOCK = `__metadata:
  version: 6
  cacheKey: 8

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: ghi789
  languageName: node
  linkType: hard
`;

const GO_MOD = `module example.com/myapp

go 1.21

require (
	github.com/gin-gonic/gin v1.9.1
	github.com/stretchr/testify v1.8.4
)

replace github.com/gin-gonic/gin => ./local/gin
`;

const GO_SUM = `github.com/gin-gonic/gin v1.9.1 h1:4idEAncQnU5cB7BeOkPtxjfCSye0AAm1R0RVIqJ+Jmg=
github.com/gin-gonic/gin v1.9.1/go.mod h1:hPys6V/FZjTp4brEKi3BcqK33XAWAW3Y+vMRuoQvLd8=
golang.org/x/crypto v0.21.0 h1:X31++rzVUdKhX5sWmSOFZxx8UW/ldWx8S51I/5Zgm38=
golang.org/x/crypto v0.21.0/go.mod h1:T0Zf+0xe53aPXKCbB5QQLAfA/GGjLwE2Um4GM5AsGSo=
`;

const CARGO_LOCK = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "serde"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3fb1c873"
`;

const CARGO_TOML = `[package]
name = "manifest-only"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
patched = { git = "https://github.com/example/patched" }
local-lib = { path = "../local-lib" }

[dev-dependencies]
criterion = "0.5"
`;

const MANIFEST_JSON = JSON.stringify({
  domain: "test_integration",
  requirements: ["requests==2.31.0", "click==8.1.3"],
});

const PYPROJECT_TOML = `[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "myapp"
version = "1.0.0"
dependencies = ["requests>=2.28.0,<3.0.0", "click==8.1.3"]
`;

const PIPFILE = `[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = ">=2.28.0"
click = "*"

[dev-packages]
pytest = "*"
`;

const SETUP_CFG = `[metadata]
name = myapp
version = 1.0.0

[options]
install_requires =
    requests>=2.28.0
    click==8.1.3
`;

const REQUIREMENTS_TXT = `requests==2.31.0
click>=8.0.0
flask~=2.0
`;

// ── detectPastedFormat ───────────────────────────────────────────────────────

describe("detectPastedFormat", () => {
  describe("npm ecosystem", () => {
    it("detects package-lock.json (v2/v3 shape) via object-valued packages entries", () => {
      assert.equal(detectPastedFormat(PACKAGE_LOCK_V2, "npm"), "package-lock.json");
    });

    it("detects package-lock.json (v1 shape) via object-valued dependencies entries", () => {
      assert.equal(detectPastedFormat(PACKAGE_LOCK_V1, "npm"), "package-lock.json");
    });

    it("detects bun.lock via array-valued packages entries", () => {
      assert.equal(detectPastedFormat(BUN_LOCK, "npm"), "bun.lock");
    });

    it("detects bun.lock when packages map is empty but a workspaces object is present", () => {
      const content = `{ "packages": {}, "workspaces": { "": {} } }`;
      assert.equal(detectPastedFormat(content, "npm"), "bun.lock");
    });

    it("detects package-lock.json when packages map is empty and no workspaces object is present", () => {
      const content = `{ "packages": {} }`;
      assert.equal(detectPastedFormat(content, "npm"), "package-lock.json");
    });

    it("detects package.json via string-valued dependencies entries", () => {
      assert.equal(detectPastedFormat(PACKAGE_JSON, "npm"), "package.json");
    });

    it("detects a bare package.json with no dependencies via name/version fields", () => {
      const content = `{ "name": "myapp", "version": "1.0.0" }`;
      assert.equal(detectPastedFormat(content, "npm"), "package.json");
    });

    it("detects pnpm-lock.yaml via its lockfileVersion header line", () => {
      assert.equal(detectPastedFormat(PNPM_LOCK, "npm"), "pnpm-lock.yaml");
    });

    it("detects yarn.lock (classic v1) via the '# yarn lockfile v1' header", () => {
      assert.equal(detectPastedFormat(YARN_CLASSIC_LOCK, "npm"), "yarn.lock");
    });

    it("detects yarn.lock (berry) via the '__metadata:' header", () => {
      assert.equal(detectPastedFormat(YARN_BERRY_LOCK, "npm"), "yarn.lock");
    });

    it("returns null for invalid JSON with no recognisable header line", () => {
      assert.equal(detectPastedFormat("not json, not yaml, just garbage text", "npm"), null);
    });

    it("returns null for a JSON array (not an npm dependency file shape)", () => {
      assert.equal(detectPastedFormat("[1, 2, 3]", "npm"), null);
    });

    it("returns null for an empty string", () => {
      assert.equal(detectPastedFormat("", "npm"), null);
    });

    it("returns null for a JSON object with none of the recognised shapes", () => {
      assert.equal(detectPastedFormat(`{ "foo": "bar" }`, "npm"), null);
    });
  });

  describe("go ecosystem", () => {
    it("detects go.mod via its leading 'module' line", () => {
      assert.equal(detectPastedFormat(GO_MOD, "go"), "go.mod");
    });

    it("detects go.sum when every non-blank line matches the module/version/hash format", () => {
      assert.equal(detectPastedFormat(GO_SUM, "go"), "go.sum");
    });

    it("returns null when some lines do not match the go.sum line format", () => {
      const content = `github.com/gin-gonic/gin v1.9.1 h1:4idEAncQnU5cB7BeOkPtxjfCSye0AAm1R0RVIqJ+Jmg=\nthis is not a go.sum line\n`;
      assert.equal(detectPastedFormat(content, "go"), null);
    });

    it("returns null for unrelated garbage content", () => {
      assert.equal(detectPastedFormat("just some random text\nwith multiple lines\n", "go"), null);
    });

    it("returns null for an empty string", () => {
      assert.equal(detectPastedFormat("", "go"), null);
    });
  });

  describe("rust ecosystem", () => {
    it("detects Cargo.lock via the '[[package]]' array-table header", () => {
      assert.equal(detectPastedFormat(CARGO_LOCK, "rust"), "Cargo.lock");
    });

    it("detects Cargo.toml via a '[package]' or '[dependencies]' section header", () => {
      assert.equal(detectPastedFormat(CARGO_TOML, "rust"), "Cargo.toml");
    });

    it("detects Cargo.toml via a '[target.*]' section header alone", () => {
      const content = `[target.'cfg(unix)'.dependencies]\nnix = "0.27"\n`;
      assert.equal(detectPastedFormat(content, "rust"), "Cargo.toml");
    });

    it("prefers Cargo.lock over Cargo.toml when both '[[package]]' and '[dependencies]' appear", () => {
      const content = `[[package]]\nname = "demo"\nversion = "0.1.0"\n\n[dependencies]\nserde = "1.0"\n`;
      assert.equal(detectPastedFormat(content, "rust"), "Cargo.lock");
    });

    it("returns null for unrelated garbage content", () => {
      assert.equal(detectPastedFormat("just some random text\n", "rust"), null);
    });

    it("returns null for an empty string", () => {
      assert.equal(detectPastedFormat("", "rust"), null);
    });
  });

  describe("python ecosystem", () => {
    it("detects manifest.json via a JSON object with a requirements array", () => {
      assert.equal(detectPastedFormat(MANIFEST_JSON, "python"), "manifest.json");
    });

    it("detects pyproject.toml via a '[project]' section header", () => {
      assert.equal(detectPastedFormat(PYPROJECT_TOML, "python"), "pyproject.toml");
    });

    it("detects Pipfile via a '[packages]' section header", () => {
      assert.equal(detectPastedFormat(PIPFILE, "python"), "Pipfile");
    });

    it("detects setup.cfg via an '[options]' section header", () => {
      assert.equal(detectPastedFormat(SETUP_CFG, "python"), "setup.cfg");
    });

    it("detects requirements.txt when a majority of candidate lines carry PEP 440 operators", () => {
      assert.equal(detectPastedFormat(REQUIREMENTS_TXT, "python"), "requirements.txt");
    });

    it("detects requirements.txt for a single bare package name with no version", () => {
      assert.equal(detectPastedFormat("requests\n", "python"), "requirements.txt");
    });

    it("does not misdetect a bare go.mod-style dependency line as requirements.txt", () => {
      const content = "github.com/gin-gonic/gin v1.9.1\n";
      assert.equal(detectPastedFormat(content, "python"), null);
    });

    it("does not misdetect a go.mod require block as requirements.txt", () => {
      assert.equal(detectPastedFormat(GO_MOD, "python"), null);
    });

    it("returns null when fewer than half the candidate lines carry PEP 440 operators", () => {
      const content = [
        "requests==2.31.0",
        "github.com/foo/bar v1.0.0",
        "github.com/baz/qux v2.0.0",
        "golang.org/x/tools v0.5.0",
      ].join("\n");
      assert.equal(detectPastedFormat(content, "python"), null);
    });

    it("returns null for a JSON object with no requirements array", () => {
      assert.equal(detectPastedFormat(`{ "domain": "test" }`, "python"), null);
    });

    it("returns null for unrelated garbage content", () => {
      assert.equal(
        detectPastedFormat(
          "just some random text\nwith no operators at all here either\n",
          "python",
        ),
        null,
      );
    });

    it("returns null for an empty string", () => {
      assert.equal(detectPastedFormat("", "python"), null);
    });
  });

  describe("unrecognised ecosystem", () => {
    it("returns null for an ecosystem value outside the known set", () => {
      assert.equal(detectPastedFormat(PACKAGE_JSON, "ruby"), null);
    });
  });
});

// ── parsePastedDependencies ──────────────────────────────────────────────────

describe("parsePastedDependencies", () => {
  describe("npm", () => {
    it("parses package-lock.json content and returns its deps with the canonical source name", async () => {
      const result = await parsePastedDependencies(PACKAGE_LOCK_V2, "npm");
      assert.equal(result.source, "package-lock.json");
      assert.ok(result.deps.some((d) => d.name === "lodash"));
    });

    it("parses bun.lock content and returns its deps with the canonical source name", async () => {
      const result = await parsePastedDependencies(BUN_LOCK, "npm");
      assert.equal(result.source, "bun.lock");
      assert.ok(result.deps.some((d) => d.name === "lodash"));
    });

    it("parses pnpm-lock.yaml content and returns its deps with the canonical source name", async () => {
      const result = await parsePastedDependencies(PNPM_LOCK, "npm");
      assert.equal(result.source, "pnpm-lock.yaml");
      assert.ok(result.deps.some((d) => d.name === "lodash"));
    });

    it("parses yarn.lock content and returns its deps with the canonical source name", async () => {
      const result = await parsePastedDependencies(YARN_CLASSIC_LOCK, "npm");
      assert.equal(result.source, "yarn.lock");
      assert.ok(result.deps.some((d) => d.name === "lodash"));
    });

    it("parses package.json content directly (non-lock format) and returns only prod deps by default", async () => {
      const result = await parsePastedDependencies(PACKAGE_JSON, "npm");
      assert.equal(result.source, "package.json");
      assert.ok(result.deps.some((d) => d.name === "lodash"));
      assert.ok(!result.deps.some((d) => d.name === "eslint"));
    });

    it("includes devDependencies from package.json when includeTests is true", async () => {
      const result = await parsePastedDependencies(PACKAGE_JSON, "npm", { includeTests: true });
      assert.ok(result.deps.some((d) => d.name === "eslint"));
    });

    it("throws an Error when the content does not match any known npm format", async () => {
      await assert.rejects(
        () => parsePastedDependencies("not a recognisable npm file", "npm"),
        /Could not recognise this as a supported npm dependency file format/,
      );
    });
  });

  describe("go", () => {
    it("parses go.mod content and returns its deps with the canonical source name", async () => {
      const result = await parsePastedDependencies(GO_MOD, "go");
      assert.equal(result.source, "go.mod");
      assert.ok(result.deps.some((d) => d.name === "github.com/gin-gonic/gin"));
    });

    it("surfaces a local-path go.mod replace directive as a dangerous dep", async () => {
      const result = await parsePastedDependencies(GO_MOD, "go");
      assert.ok(result.dangerousDeps.some((d) => d.reason === "local path replace"));
    });

    it("parses go.sum content and returns its deps with the canonical source name", async () => {
      const result = await parsePastedDependencies(GO_SUM, "go");
      assert.equal(result.source, "go.sum");
      assert.ok(result.deps.some((d) => d.name === "golang.org/x/crypto"));
    });

    it("throws an Error when the content does not match any known Go format", async () => {
      await assert.rejects(
        () => parsePastedDependencies("not a recognisable go file", "go"),
        /Could not recognise/,
      );
    });
  });

  describe("rust", () => {
    it("parses Cargo.lock content and returns its deps with the canonical source name", async () => {
      const result = await parsePastedDependencies(CARGO_LOCK, "rust");
      assert.equal(result.source, "Cargo.lock");
      assert.ok(result.deps.some((d) => d.name === "serde"));
    });

    it("parses Cargo.toml content and returns its deps plus non-registry dangerousDeps", async () => {
      const result = await parsePastedDependencies(CARGO_TOML, "rust");
      assert.equal(result.source, "Cargo.toml");
      assert.ok(result.deps.some((d) => d.name === "serde"));
      assert.ok(result.dangerousDeps.some((d) => d.reason === "git dependency"));
      assert.ok(result.dangerousDeps.some((d) => d.reason === "path dependency"));
    });

    it("throws an Error when the content does not match any known Rust format", async () => {
      await assert.rejects(
        () => parsePastedDependencies("not a recognisable rust file", "rust"),
        /Could not recognise/,
      );
    });
  });

  describe("python", () => {
    it("parses pyproject.toml content and returns its deps with the canonical source name", async () => {
      const result = await parsePastedDependencies(PYPROJECT_TOML, "python");
      assert.equal(result.source, "pyproject.toml");
      assert.ok(result.deps.some((d) => d.name === "requests"));
    });

    it("parses Pipfile content and returns its deps with the canonical source name", async () => {
      const result = await parsePastedDependencies(PIPFILE, "python");
      assert.equal(result.source, "Pipfile");
      assert.ok(result.deps.some((d) => d.name === "requests"));
    });

    it("parses setup.cfg content and returns its deps with the canonical source name", async () => {
      const result = await parsePastedDependencies(SETUP_CFG, "python");
      assert.equal(result.source, "setup.cfg");
      assert.ok(result.deps.some((d) => d.name === "requests"));
    });

    it("parses manifest.json content and returns its deps with the canonical source name", async () => {
      const result = await parsePastedDependencies(MANIFEST_JSON, "python");
      assert.equal(result.source, "manifest.json");
      assert.ok(result.deps.some((d) => d.name === "requests"));
    });

    it("parses requirements.txt content and returns its deps with the canonical source name", async () => {
      const result = await parsePastedDependencies(REQUIREMENTS_TXT, "python");
      assert.equal(result.source, "requirements.txt");
      assert.ok(result.deps.some((d) => d.name === "requests"));
      assert.equal(result.note, null);
    });

    it("surfaces skipped '-r' include lines as a note instead of dropping them silently", async () => {
      const content = `requests==2.31.0\n-r dev-requirements.txt\nclick>=8.0.0\n`;
      const result = await parsePastedDependencies(content, "python");
      assert.equal(result.source, "requirements.txt");
      assert.match(result.note, /Skipped 1 '-r'\/'--requirement' include line/);
      assert.match(result.note, /cannot be resolved from pasted text/);
    });

    it("surfaces multiple skipped '--requirement' include lines with a pluralised count in the note", async () => {
      const content = `requests==2.31.0\n--requirement dev.txt\n-r test.txt\nclick>=8.0.0\n`;
      const result = await parsePastedDependencies(content, "python");
      assert.match(result.note, /Skipped 2 '-r'\/'--requirement' include lines/);
    });

    it("captures a PEP 508 URL requirement from requirements.txt as a dangerous dep", async () => {
      const content = `requests==2.31.0\ninternal-auth @ https://artifacts.corp.invalid/internal-auth-1.0.0.whl\n`;
      const result = await parsePastedDependencies(content, "python");
      assert.ok(result.dangerousDeps.some((d) => d.name === "internal-auth"));
    });

    it("throws an Error when the content does not match any known Python format", async () => {
      await assert.rejects(
        () => parsePastedDependencies("just some random text\nwith no operators here\n", "python"),
        /Could not recognise this as a supported python dependency file format/,
      );
    });
  });
});
